{
    'name': 'Clio Vigil — Mediebevakning',
    'version': '19.0.1.6.0',
    'summary': 'Odoo-vy för clio-vigil: källor, pipeline-kö och färdiga bevakningsobjekt',
    'author': 'Arvas International AB',
    'depends': ['contacts', 'clio_cockpit', 'clio_media'],
    'data': [
        'security/ir.model.access.csv',
        'views/clio_vigil_source_views.xml',
        'views/clio_vigil_item_views.xml',
        'views/clio_vigil_subscriber_views.xml',
        'views/clio_vigil_wizard_views.xml',
        'views/clio_vigil_pipeline_views.xml',
        'views/clio_media_article_vigil_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
