{
    "name":        "Clio UAP Tracking",
    "version":     "19.0.1.5.0",
    "category":    "Research",
    "summary":     "UAP encounter tracking, multi-classification, anomaly index and transmorf taxonomy.",
    "author":      "Fredrik Arvas / Arvas International AB",
    "license":     "LGPL-3",
    "url": "https://github.com/FredrikArvas/clio-odoo-addons",
    "depends":     ["base", "contacts", "clio_media"],
    "data": [
        "security/ir.model.access.csv",
        "views/uap_source_views.xml",
        "views/uap_witness_views.xml",
        "views/uap_database_views.xml",
        "views/uap_series_views.xml",
        "views/uap_verification_views.xml",
        "views/uap_transmorf_entity_views.xml",
        "views/uap_encounter_classification_views.xml",
        "views/uap_encounter_views.xml",
        "views/uap_anomaly_views.xml",
        "views/uap_menus.xml",
        "views/uap_media_article_views.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application":  True,
}
