{
    "name":        "Clio Recruit — Passiv kandidatsourcing",
    "version":     "19.0.2.0.0",
    "category":    "Extra Tools",
    "summary":     "Odoo-vy for clio-recruiter: rekryterarprofiler och matchhistorik.",
    "author":      "Arvas International AB",
    "license":     "LGPL-3",
    "depends":     ["contacts", "clio_cockpit", "clio_media"],
    "data": [
        "security/ir.model.access.csv",
        "data/clio_recruiter_candidate_type_data.xml",
        "views/clio_recruiter_profile_views.xml",
        "views/clio_recruiter_match_views.xml",
        "views/res_partner_views.xml",
        "views/menu.xml",
    ],
    "installable":  True,
    "auto_install": False,
    "application":  False,
}
